RestorantMVC/Models/LayoutViewModel.cs
using Entites.Concrate;

namespace RestorantMVC.Models
{
    public class LayoutViewModel
    {
        public ICollection<Kategori> Kategoriler { get; set; }
    }
}

RestorantMVC/Controllers/KategoriController.cs
using DAL.Contexts;
using Entites.Abstract;
using Entites.Concrate;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace RestorantMVC.Controllers
{
    public class KategoriController : Controller
    {
        public readonly SqlDbContext dbContext;

        public KategoriController(SqlDbContext sqlDbContext)
        {
            this.dbContext = sqlDbContext;
        }

        public IActionResult Index()
        {
            var result = dbContext.Kategoriler.ToList();
            return View(result);
        }

        [HttpGet]
        public IActionResult Add() 
        {
            Kategori kategori = new();
            return View(kategori);
        }

        [HttpPost]
        public IActionResult Add(Kategori kategori)
        {
            if(ModelState.IsValid)
            {
                return View(kategori);
            }

            try
            {
                dbContext.Kategoriler.Add(kategori);
                dbContext.SaveChanges();
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("" , "beklenmedik bir hata oluştu, lütfen daha sonra tekrar deneyiniz.");
                return View(kategori);
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            var kategori = dbContext.Kategoriler.Find(id);
            return View(kategori);
        }

        [HttpPost]
        public IActionResult Update(Kategori kategori)
        {
            if(ModelState.IsValid)
            {
                return View(kategori);
            }
            else
            {
                dbContext.Kategoriler.Update(kategori);
                dbContext.SaveChanges();
                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var kategori = dbContext.Kategoriler.Find(id);
            return View(kategori);
        }

        [HttpPost]
        public IActionResult Delete(Kategori kategori)
        {
            if (ModelState.IsValid)
            {
                return View(kategori);
            }
            else
            {
                dbContext.Kategoriler.Remove(kategori);
                dbContext.SaveChanges();
                return RedirectToAction("Index");
            }
        }
    }
}

RestorantMVC/Controllers/SiparisController.cs
using DAL.Contexts;
using Entites.Concrate;
using Microsoft.AspNetCore.Mvc;

namespace RestorantMVC.Controllers
{
    public class SiparisController : Controller
    {
        private readonly SqlDbContext dbContext;

        public SiparisController(SqlDbContext dbContext)
        {
            this.dbContext = dbContext;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Ekle(Urun urunler)
        {

            return RedirectToAction("Index");
        }
    }
}

RestorantMVC/Controllers/UrunController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DAL.Contexts;
using Entites.Concrate;

namespace RestorantMVC.Controllers
{
    public class UrunController : Controller
    {
        private readonly SqlDbContext _context;

        public UrunController(SqlDbContext context)
        {
            _context = context;
        }

        // GET: Urun
        public async Task<IActionResult> Index()
        {
            var sqlDbContext = _context.Urunler.Include(u => u.Kategori);
            return View(await sqlDbContext.ToListAsync());
        }

        // GET: Urun/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Urunler == null)
            {
                return NotFound();
            }

            var urun = await _context.Urunler
                .Include(u => u.Kategori)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (urun == null)
            {
                return NotFound();
            }

            return View(urun);
        }

        
    }
}

RestorantMVC/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RestorantMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RestorantMVC.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCareas.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RestorantMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Kategori" asp-action="Index">Admin/Kategori</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Urun" asp-action="Index">Admin/Urun</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Siparis" asp-action="Index">Admin/Siparis</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - RestorantMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>